image: registry.gitlab.com/floscher/gradle-josm-plugin/java8:latest

before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

assemble:
  stage: build
  script:
  - ./gradlew assemble
  artifacts:
    untracked: true

test:
  stage: test
  script:
  - ./gradlew build dokka
  artifacts:
    untracked: true

publishPlugin:
  stage: deploy
  script:
  - ./gradlew -Pgradle.publish.secret="$GRADLE_PUBLISH_SECRET" -Pgradle.publish.key="$GRADLE_PUBLISH_KEY" publishPlugins
  dependencies:
  - test
  only:
  - tags@floscher/gradle-josm-plugin

pages:
  stage: deploy
  script:
  - |
    mkdir -p ~/.ssh/
    echo "$SSH_GITLAB_PUBLIC_KEY" >> ~/.ssh/known_hosts
    echo "$SSH_DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa
    chmod -R 600 ~/.ssh
    git clone --depth 1 --branch pages git@gitlab.com:floscher/gradle-josm-plugin.git public
  - |
    version=`git describe --always --dirty`
    longVersion=`git describe --always --long --dirty`
    rm -rf build/maven/
    mv public/maven/ build/maven/
    ./gradlew publish dokka
    mv build/maven/ public/maven/
    mv build/docs/kdoc/ "public/kdoc/$version/"
  - |
    cd public/
    git rm --ignore-unmatch kdoc/current kdoc/latest
    ln -s "./$version" kdoc/current
    ln -s "./$version" kdoc/latest
    git stage .
  - |
    git config user.name "Deploy with GitLab CI"
    git config user.email "deploy@gitlab.com"
    git commit -a -m "Update Maven repository and KDoc documentation to $longVersion"
    git push origin pages
  dependencies:
  - test
  artifacts:
    paths:
    - public
  only:
  - tags@floscher/gradle-josm-plugin
