image: openjdk:8-jdk-alpine

before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

assemble:
  stage: build
  script:
  - ./gradlew assemble
  artifacts:
    untracked: true

build:
  stage: test
  script:
  - ./gradlew build

minJosm:
  stage: test
  script:
  - ./gradlew compileJava_minJosm

latestJosm:
  stage: test
  script:
  - ./gradlew compileJava_latestJosm
